"""initial schema

Creates all 9 tables: user, question, option, exam, exam_question,
exam_assignment, submission, answer, refresh_token.

NFR-3 (single-tenant): no `organization_id` column exists anywhere.

Hand-written rather than autogenerated (no Python/Postgres available in the
authoring environment); kept in lock-step with
`app/infrastructure/db/models/`.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'user')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)

    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "option",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "is_correct", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_option_question_id"), "option", ["question_id"], unique=False
    )

    op.create_table(
        "exam",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "exam_question",
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exam.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("exam_id", "question_id"),
    )

    op.create_table(
        "exam_assignment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exam_id"], ["exam.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # FR-5: an exam is assigned to a given user at most once.
        sa.UniqueConstraint(
            "exam_id", "user_id", name="uq_exam_assignment_exam_id_user_id"
        ),
    )
    op.create_index(
        op.f("ix_exam_assignment_exam_id"),
        "exam_assignment",
        ["exam_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exam_assignment_user_id"),
        "exam_assignment",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exam_assignment_id", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_assignment_id"], ["exam_assignment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        # FR-6: single attempt — one submission per assignment.
        sa.UniqueConstraint(
            "exam_assignment_id", name="uq_submission_exam_assignment_id"
        ),
    )

    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("selected_option_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_correct", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"]),
        sa.ForeignKeyConstraint(["selected_option_id"], ["option.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_submission_id"), "answer", ["submission_id"], unique=False
    )

    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_token_token_hash"),
        "refresh_token",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_token_family_id"),
        "refresh_token",
        ["family_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_refresh_token_family_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_token_hash"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_table("refresh_token")

    op.drop_index(op.f("ix_answer_submission_id"), table_name="answer")
    op.drop_table("answer")

    op.drop_table("submission")

    op.drop_index(
        op.f("ix_exam_assignment_user_id"), table_name="exam_assignment"
    )
    op.drop_index(
        op.f("ix_exam_assignment_exam_id"), table_name="exam_assignment"
    )
    op.drop_table("exam_assignment")

    op.drop_table("exam_question")
    op.drop_table("exam")

    op.drop_index(op.f("ix_option_question_id"), table_name="option")
    op.drop_table("option")

    op.drop_table("question")

    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
